
import NavBar from "./components/NavBar";
import "./globals.css";
import clsx from "clsx";
import { Inter } from "next/font/google";
import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="en">
        <body
          className={clsx(inter.className, "bg-slate-700")}>
          <NavBar />
          <main className="h-screen p-16">{children}</main>
        </body>
      </html>
    </ClerkProvider>







  );
}
